Repository cylc/release-actions, pull requests merged in 2021-08, with the labels that each got.

#18 Ignore [bot] in grep for shortlog
  check-shortlog/action.yml
Labels: small

#19 Use unified diff for shortlog
  check-shortlog/action.yml
Labels: small

#21 Stop using master branch; use current versioned branch as default branch
  README.md
Labels: question, small

#22 Add input for showing GH workflow badges in release PR
  stage-1/create-release-pr/action.yml
  stage-1/create-release-pr/create-release-pr.js
Labels: enhancement
